### ISSUE TITLE
type-a-number-js - is broken

### ISSUE THREAD

**Issue by michael-nischt** [playgameservices/web-basic-samples#10]
Refused to display 'https://accounts.google.com/o/oauth2/auth?client_id=123456789012.apps.googl…in=http%3A%2F%2Flocalhost%3A8000&state=860935219%7C0.3607698553&authuser=0' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN

I suppose Google's server stopped permitting cross-origin framing.

**Comment by gguuss** [comment]
The client_id parameter looks wrong. Did you configure the sample by setting all the values in `js/constants.js` and `index.html`?  Most notably, the client ID in index.html looks like it has not been set.

**Comment by michael-nischt** [comment]
Thanks, looks like that's the issue. The client id seemed valid to me so I didn't think I had to go through all the hassle of creating a dummy application and replacing it just to try out the example..

**Comment by TheMaverickProgrammer** [comment]
This needs to be documented. I was experiencing the same issue and didn't think about creating a dummy app.
