### ISSUE TITLE
Error 500 Message:Null

### ISSUE THREAD

**Issue by Spirit30** [playgameservices/web-basic-samples#18]
Details:
https://stackoverflow.com/questions/54814583/google-api-google-play-services-error-500-messagenull/54814780#54814780

How to fix or workaround?

**Comment by GeoRepoWeb** [comment]
Any reply?

I just want to check User ID received from Client App on Server.
Why is this so over-complicated, it took 10 minutes from me using Facebook Graph API.

Can you be so kind to let me know how I can do it without all this "secure" crap which unfortunately doesn't work at all even in API Explorer?

I'm sorry for strait forward.
But I'm just want to verify User ID received from Client App.
Can you tell me how to do it?

**Comment by Spirit30** [comment]
Any reply?

I just want to check User ID received from Client App on Server.
Why is this so over-complicated, it took 10 minutes from me using Facebook Graph API.

Can you be so kind to let me know how I can do it without all this "secure" crap which unfortunately doesn't work at all even in API Explorer?

I'm sorry for strait forward.
But I'm just want to verify User ID received from Client App.
Can you tell me how to do it?
